#List of curio slot type settings
[[curiosSettings]]
identifier = "bracelet"
size = 2
override = true

[[curiosSettings]]
identifier = "ring"
size = 5
override = true

[[curiosSettings]]
identifier = "charm"
size = 5
override = true

[[curiosSettings]]
identifier = "head"
size = 2
override = true

[[curiosSettings]]
identifier = "necklace"
size = 2
override = true

[[curiosSettings]]
identifier = "belt"
size = 2
override = true

[[curiosSettings]]
identifier = "angelring"
override = true

[[curiosSettings]]
identifier = "elytra"
size = 1
override = true

